---
Name: silvercommercecurrencyswitcherconfig
---
## Extensions
SilverStripe\Security\Member:
  extensions:
    - SilverCommerce\CurrencySwitcher\Extensions\MemberExtension
---
Before: 
  - '#silvercommercesettingsconfig'
---
SilverStripe\Control\Controller:
  extensions:
    - SilverCommerce\CurrencySwitcher\Extensions\ControllerExtension